

export const TOPIC_CONTENT_TREE_PUBLISH = "CONTENT_TREE_PUBLISH";

export const TOPIC_CONTENT_DOCUMENT_PUBLISH = "CONTENT_DOCUMENT_PUBLISH";

export const TOPIC_PROTOTYPE_PUBLISH = "CONTENT_DOCUMENT_PUBLISH";
